import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import pool from '../db.js';
import { getOnboardingStatus, createOpeningWallet, assertTransactionReady, completeDashboardTour } from '../services/onboardingActivationService.js';
const enabled = process.env.FINEPRO_DB_INTEGRATION === '1';
async function fixture({ role='owner', required=true }={}) {
 const suffix=crypto.randomUUID();
 const owner=await pool.query(`INSERT INTO users(email,name,password_hash,email_verified_at) VALUES($1,'QA Activation','qa',now()) RETURNING id`,[`qa-activation-${suffix}@example.invalid`]);
 const ownerId=owner.rows[0].id;
 const h=await pool.query(`INSERT INTO households(name,owner_id,household_type) VALUES($1,$2,'individual') RETURNING id`,[`QA-ACT-${suffix.slice(0,8)}`,ownerId]); const householdId=h.rows[0].id;
 await pool.query(`UPDATE household_onboarding SET activation_required=$2 WHERE household_id=$1`,[householdId,required]);
 if(role==='member'){const m=await pool.query(`INSERT INTO users(email,name,password_hash,email_verified_at) VALUES($1,'QA Member','qa',now()) RETURNING id`,[`qa-member-${suffix}@example.invalid`]);await pool.query(`INSERT INTO household_members(household_id,user_id,role) VALUES($1,$2,'member')`,[householdId,m.rows[0].id]);return{householdId,userId:m.rows[0].id,ownerId,memberId:m.rows[0].id};}
 return{householdId,userId:ownerId,ownerId};
}
async function cleanup(f){if(f?.householdId)await pool.query('DELETE FROM households WHERE id=$1',[f.householdId]);if(f?.memberId)await pool.query('DELETE FROM users WHERE id=$1',[f.memberId]);if(f?.ownerId)await pool.query('DELETE FROM users WHERE id=$1',[f.ownerId]);}
test('new owner blocked until opening wallet baseline exists',{skip:!enabled},async()=>{const f=await fixture();try{const before=await getOnboardingStatus(f.userId);assert.equal(before.role,'owner');assert.equal(before.transaction_ready,false);await assert.rejects(assertTransactionReady(f.householdId),e=>e.code==='HOUSEHOLD_SETUP_REQUIRED');const made=await createOpeningWallet({householdId:f.householdId,userId:f.userId,name:'Tunai QA',actualBalance:125000,idempotencyKey:crypto.randomUUID()});assert.equal(made.wallet.balance,125000);const after=await getOnboardingStatus(f.userId);assert.equal(after.wallet_setup_completed,true);assert.equal(after.transaction_ready,true);await assert.doesNotReject(assertTransactionReady(f.householdId));}finally{await cleanup(f);}});
test('opening balance zero valid, audited, creates no transaction',{skip:!enabled},async()=>{const f=await fixture();try{const before=await pool.query('SELECT count(*)::int count FROM transactions');const made=await createOpeningWallet({householdId:f.householdId,userId:f.userId,name:'Kosong QA',actualBalance:0,idempotencyKey:crypto.randomUUID()});assert.equal(made.wallet.balance,0);const audit=await pool.query(`SELECT entry_type,adjustment_amount FROM wallet_reconciliations WHERE wallet_id=$1`,[made.wallet.id]);assert.equal(audit.rows[0].entry_type,'opening_balance');assert.equal(Number(audit.rows[0].adjustment_amount),0);const after=await pool.query('SELECT count(*)::int count FROM transactions');assert.equal(after.rows[0].count,before.rows[0].count);}finally{await cleanup(f);}});
test('member cannot create opening wallet and inherits owner readiness',{skip:!enabled},async t=>{const f=await fixture({role:'member'});if(f.skipMember)return t.skip('no second user fixture');try{await assert.rejects(createOpeningWallet({householdId:f.householdId,userId:f.userId,name:'Forbidden',actualBalance:1,idempotencyKey:crypto.randomUUID()}),e=>e.code==='ONBOARDING_OWNER_REQUIRED');const s=await getOnboardingStatus(f.userId);assert.equal(s.role,'member');assert.equal(s.transaction_ready,false);}finally{await cleanup(f);}});
test('legacy household without mandatory activation stays transaction-ready',{skip:!enabled},async()=>{const f=await fixture({required:false});try{const s=await getOnboardingStatus(f.userId);assert.equal(s.activation_required,false);assert.equal(s.transaction_ready,true);await assert.doesNotReject(assertTransactionReady(f.householdId));}finally{await cleanup(f);}});
test('dashboard tour completion persists per user',{skip:!enabled},async()=>{const f=await fixture();try{await createOpeningWallet({householdId:f.householdId,userId:f.userId,name:'Tour QA',actualBalance:10,idempotencyKey:crypto.randomUUID()});await completeDashboardTour(f.householdId,f.userId,1);const s=await getOnboardingStatus(f.userId);assert.equal(s.dashboard_tour_completed,true);assert.equal(s.onboarding_version,1);}finally{await cleanup(f);}});
test.after(async()=>{await pool.end();});
