import { useMemo, useState } from 'react';
import { ArrowRight, CheckCircle2, Landmark, ShieldCheck, Sparkles, Wallet } from 'lucide-react';
import { createOpeningWallet } from '../api/onboarding.js';

function formatInput(value){const digits=String(value||'').replace(/\D/g,'');return digits?new Intl.NumberFormat('id-ID').format(Number(digits)):'';}
function numberValue(value){return Number(String(value||'').replace(/\D/g,''))||0;}

export default function ActivationWizard({status,onReady}){
 const [step,setStep]=useState('welcome'); const [name,setName]=useState(''); const [balance,setBalance]=useState(''); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 const amount=useMemo(()=>numberValue(balance),[balance]);
 if(!status?.activation_required||status.transaction_ready)return null;
 if(status.role!=='owner')return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-navy/65 p-4 backdrop-blur-sm sm:items-center"><div className="w-full max-w-md rounded-[30px] bg-white p-6 shadow-2xl" role="dialog" aria-modal="true"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-light text-violet"><ShieldCheck/></div><h2 className="mt-4 text-xl font-bold text-navy">Menunggu pemilik household</h2><p className="mt-2 text-sm leading-6 text-neutral-500">Pemilik perlu membuat dompet dan menetapkan saldo awal. Setelah selesai, kamu bisa mencatat transaksi bersama.</p><button onClick={()=>window.location.reload()} className="mt-5 h-12 w-full rounded-full bg-violet font-bold text-white">Cek Lagi</button></div></div>;
 async function submit(e){e.preventDefault();if(!name.trim())return;setSaving(true);setError('');try{const key=crypto.randomUUID();await createOpeningWallet({name:name.trim(),actual_balance:amount,idempotency_key:key});setStep('done');}catch(err){setError(err.message);}finally{setSaving(false);}}
 return <div className="fixed inset-0 z-[80] flex items-end justify-center overflow-y-auto bg-navy/65 p-4 backdrop-blur-sm sm:items-center">
  <div className="w-full max-w-md rounded-[32px] bg-white p-6 shadow-2xl" role="dialog" aria-modal="true" aria-label="Pengaturan awal FinePro">
   {step==='welcome'&&<><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-light text-violet"><Sparkles/></div><div className="mt-4 text-xs font-bold uppercase tracking-[.18em] text-violet">Aktivasi 1 dari 2</div><h2 className="mt-2 text-2xl font-bold leading-tight text-navy">Siapkan titik awal keuanganmu</h2><p className="mt-3 text-sm leading-6 text-neutral-500">Sebelum transaksi pertama, buat satu dompet dan masukkan saldo nyata saat ini. FinePro akan memulai laporan dari angka yang akurat.</p><div className="mt-5 grid gap-2"><div className="flex gap-3 rounded-2xl bg-neutral-50 p-3"><Wallet className="text-violet" size={20}/><div><b className="text-sm text-navy">Buat dompet pertama</b><p className="text-xs text-neutral-500">Tunai, rekening bank, atau e-wallet.</p></div></div><div className="flex gap-3 rounded-2xl bg-neutral-50 p-3"><Landmark className="text-mint" size={20}/><div><b className="text-sm text-navy">Tetapkan saldo awal</b><p className="text-xs text-neutral-500">Bukan pemasukan atau pengeluaran.</p></div></div></div><button onClick={()=>setStep('wallet')} className="mt-6 flex h-12 w-full items-center justify-center gap-2 rounded-full bg-violet font-bold text-white">Mulai Pengaturan <ArrowRight size={17}/></button></>}
   {step==='wallet'&&<form onSubmit={submit}><div className="text-xs font-bold uppercase tracking-[.18em] text-violet">Aktivasi 2 dari 2</div><h2 className="mt-2 text-2xl font-bold text-navy">Dompet dan saldo awal</h2><p className="mt-2 text-sm leading-6 text-neutral-500">Masukkan saldo aktual. Saldo Rp0 tetap valid bila dompet memang kosong.</p><label className="mt-5 block text-xs font-bold text-neutral-600" htmlFor="activation-wallet-name">Nama dompet</label><input id="activation-wallet-name" autoFocus required maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="Contoh: Tunai, BCA, DANA" className="mt-1 h-12 w-full rounded-2xl border border-neutral-border bg-neutral-50 px-4 text-sm outline-none focus:border-violet"/><label className="mt-4 block text-xs font-bold text-neutral-600" htmlFor="activation-opening-balance">Saldo aktual saat ini</label><div className="mt-1 flex h-12 items-center rounded-2xl border border-neutral-border bg-neutral-50 px-4 focus-within:border-violet"><span className="font-bold text-neutral-500">Rp</span><input id="activation-opening-balance" inputMode="numeric" value={balance} onChange={e=>setBalance(formatInput(e.target.value))} placeholder="0" className="h-full min-w-0 flex-1 bg-transparent px-2 text-lg font-bold text-navy outline-none"/></div><div className="mt-4 rounded-2xl bg-mint-light p-3 text-xs leading-5 text-mint"><b>Baseline aman:</b> saldo awal dicatat dalam ledger khusus dan tidak masuk statistik pemasukan atau pengeluaran.</div>{error&&<div className="mt-3 rounded-xl bg-coral-light p-3 text-xs font-semibold text-coral">{error}</div>}<div className="mt-6 flex gap-2"><button type="button" onClick={()=>setStep('welcome')} disabled={saving} className="h-12 flex-1 rounded-full border border-neutral-border font-bold text-neutral-600">Kembali</button><button type="submit" disabled={saving||!name.trim()} className="h-12 flex-[1.5] rounded-full bg-violet font-bold text-white disabled:opacity-50">{saving?'Menyiapkan...':'Tetapkan Saldo Awal'}</button></div></form>}
   {step==='done'&&<><div className="flex h-14 w-14 items-center justify-center rounded-full bg-mint-light text-mint"><CheckCircle2 size={30}/></div><h2 className="mt-4 text-2xl font-bold text-navy">FinePro siap digunakan</h2><div className="mt-4 grid gap-2 text-sm"><div className="flex items-center gap-2 text-neutral-600"><CheckCircle2 size={17} className="text-mint"/> Dompet pertama dibuat</div><div className="flex items-center gap-2 text-neutral-600"><CheckCircle2 size={17} className="text-mint"/> Saldo awal Rp{new Intl.NumberFormat('id-ID').format(amount)} ditetapkan</div><div className="flex items-center gap-2 text-neutral-600"><CheckCircle2 size={17} className="text-mint"/> Siap mengenal dashboard</div></div><button onClick={onReady} className="mt-6 flex h-12 w-full items-center justify-center gap-2 rounded-full bg-violet font-bold text-white">Lihat Panduan Dashboard <ArrowRight size={17}/></button></>}
  </div>
 </div>;
}
